In [36]:
# Numpy(Numerical Python)
# 과학, 공학 연산을 쉽게 하도록 지원하는 다차원 배열(multi-dimensional array)라이브러리
# Numpy를 사용해서 대규모 배열 처리를 쉽게 하도록 하고, 파이썬 List 와는 차이가 있다.

import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([[1,2,3],[4,5,6]])

print(a)
print(b)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [8]:
arr1 = np.zeros(5)
print(arr1)

arr2 = np.zeros((2,8))
print(arr2)

arr3 = np.zeros((3,3,3))
print(arr3)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [11]:
arr1 = np.ones(5)
print(arr1)

arr2 = np.ones((10,10))
print(arr2)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [12]:
arr3 = np.empty(5)
print(arr3)

arr4 = np.empty((3,3))
print(arr4)

[1. 1. 1. 1. 1.]
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 7.01573217e-321]
 [6.95250701e-310 0.00000000e+000 6.95268724e-310]]


In [13]:
arr1 = np.arange(5)
print(arr1)

arr2 = np.arange(3,10)
print(arr2)

arr3 = np.arange(1,10,0.2)
print(arr3)

[0 1 2 3 4]
[3 4 5 6 7 8 9]
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [15]:
arr1 = np.linspace(0,1,5)
print(arr1)

arr2 = np.linspace(-10,10,10)
print(arr2)

[0.   0.25 0.5  0.75 1.  ]
[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [35]:
# 변환 함수
#  배열 형태 변환
# 1차원 배열을 2차로 변환
arr1= np.array([1,2,3,4,5,6])
arr2 =arr1.reshape(2,3)
print(arr2)
# 2차원 배열을 1차원 배열로 변환
arr1= arr2.flatten()
print(arr1)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [20]:
# 타입변환
# 정수를 실수로 변환
arr_int = np.array([1,2,3])
arr_float = arr_int.astype(float)

print(arr_float)

# 문자열 배열을 정수형 배열로 변환
arr_str = np.array(['1','2','3'])
arr_int = arr_str.astype(int)
print(arr_int)

[1. 2. 3.]
[1 2 3]


In [24]:
# 축 변환
b = np.array([[1,2],[3,4],[5,6]])
trans = b. transpose()
print(trans)

print(np.transpose(trans))

[[1 3 5]
 [2 4 6]]
[[1 2]
 [3 4]
 [5 6]]


In [29]:
# 집계함수

print(b)
print(b.sum())
print(b.mean())
print(b.std())
print(b.max())
print(b.min())
print(b.argmax())
print(b.argmin())

[[1 2]
 [3 4]
 [5 6]]
21
3.5
1.707825127659933
6
1
5
0


In [30]:
# 논리함수
arr1 = np.array([True, False, False, True])
arr2 = np.array([True, True, False, False])

print(np.logical_and(arr1,arr2))
print(np.logical_or(arr1, arr2))
print(np.logical_not(arr1))
print(np.logical_not(arr2))

[ True False False False]
[ True  True False  True]
[False  True  True False]
[False False  True  True]
